### ISSUE TITLE
Export for Grandstream phones has wrong encoding

### ISSUE THREAD

**Issue by jkischel** [Rillke/Contact-Conversion-Wizard#10]
Encoding for Grandstream GXP phones is expected to be UTF8, but is currently ANSI.

**Comment by tryallthethings** [comment]
Just had a quick look at the code and you seem to be correct. This should be a rather quick fix. 
Would you mind verifying a fix? If so I would send you a version.

**Comment by tryallthethings** [comment]
@jkischel 
Please try with v3.5.0.1 https://github.com/Rillke/Contact-Conversion-Wizard/releases/tag/3.5.0.1

**Comment by jkischel** [comment]
yep, looks good.
