### ISSUE TITLE
Contacts without phone number not read from Outlook

### ISSUE THREAD

**Issue by a-einstein** [Rillke/Contact-Conversion-Wizard#14]
I always read my contacts from Outlook, which is leading for me.

I went through the roof because a newly added contact was not exported. I only noticed after I imported the resulting file into my phone.

I took me quite some time, after trying a couple of things, to notice it was not read because it had no phone number. Adding a zero as a number worked around that. I don't seem to be able to configure this behaviour.

But I don't get that. I might not have a number yet, but just an e-address, or maybe not even that but a physical address or whatever. I want to be able to convert it anyway and import it into my phone, or elsewhere.

So that's my request.

**Comment by tryallthethings** [comment]
I'm added this as a configurable feature. You'll be able to select if you want to export contacts with empty names and / or numbers from Outlook. 
The original author added multiple checks if a contact has a number and / or name and ignores those contacts. Most imports / exports would need to be changed.
For now, I would only add this for the export format you're using since you're the one requesting it.

**Comment by tryallthethings** [comment]
Please try with https://github.com/Rillke/Contact-Conversion-Wizard/releases/tag/3.5.0.2

**Comment by tryallthethings** [comment]
@a-einstein Did you get a chance to try this?

**Comment by a-einstein** [comment]
Seems to work in 3.5.0.2.
- I can import from Outlook with a record without a phone number, and even without an e-address. 
- I can export to VCF.
- I cannot export to FritzBox. Which makes sense as that revolves around the Dect-phone.

**Comment by tryallthethings** [comment]
Thank you for testing. I'll look into the Fritz!Box Export for the next version.

**Comment by Rillke** [comment]
Thanks for the report. #15 by @tryallthethings fixed the reported issue. @a-einstein Can you please create a new issue for the FritzBox here on GitHub?
