### ISSUE TITLE
VCF UTF-8-BOM/UTF-8

### ISSUE THREAD

**Issue by a-einstein** [Rillke/Contact-Conversion-Wizard#2]
CCW 3.5.0.0 installed from elsewhere.

I just discovered exporting into VCF, which would come in very handy.

When trying to opening the file I got Live Mail 2012 installing and reporting it not to be a valid vCard. When trying it on Android I got a parse error about the start of the file.

Opening it in Notepad++ I noticed it was encoded in UTF-8-BOM (which I did not know at the time). Converting it into UTF-8 and retrying, it was accepted by Live Mail (but I got hell by masses of popups. But more importantly: it als worked on Android.

So: it seems it better be simple UTF-8.

By the way, I may help on this project, because I use it myself. To start with on this issue.

**Comment by a-einstein** [comment]
Sorry I did not react so far. It might take a while I can turn into this.

**Comment by a-einstein** [comment]
Great you already seemed to have fixed this bug.

**Comment by tryallthethings** [comment]
Are you sure this is fixed? I only changed the UTF export for Grandstream phones in #10

**Comment by tryallthethings** [comment]
Please try with https://github.com/Rillke/Contact-Conversion-Wizard/releases/tag/3.5.0.2
Regular .vcf are now exported as UTF-8 (without BOM)

**Comment by tryallthethings** [comment]
@a-einstein Did you get a chance to try this?

**Comment by a-einstein** [comment]
> @a-einstein Did you get a chance to try this?

I had not, I had just read the release notes of 3.5.0.1.
After using it turned out NOT to have been fixed.

I will try 3.5.0.2.

**Comment by a-einstein** [comment]
Yep, 3.5.0.2 DOES work!

Thanks.

**Comment by tryallthethings** [comment]
Thank you for the feedback!

> But you seem to not have updated the version number, it still shows 3.5.0.1.
You are absolutely correct. Forgot to bump the version number up. Good catch!
