### ISSUE TITLE
Projektdatei / Build instructions / Project file

### ISSUE THREAD

**Issue by Rillke** [Rillke/Contact-Conversion-Wizard#3]
The project needs a project build file. Decompiling the latest windows binary with JetBrains.dotPeek.2018.2.3 revealed lots of dependencies which aren't yet included:

```
> tree
├───Contact_Conversion_Wizard
│   └───Properties
├───Google
│   ├───Contacts
│   └───GData
│       ├───Client
│       │   ├───ResumableUpload
│       │   └───Util
│       ├───Contacts
│       └───Extensions
│           ├───AppControl
│           ├───Apps
│           ├───Exif
│           ├───Location
│           └───MediaRss
├───LinqBridge
├───LumenWorks
│   └───Framework
│       └───IO
│           └───Csv
│               └───Resources
├───Microsoft
│   └───Office
│       ├───Core
│       └───Interop
│           └───Outlook
├───Newtonsoft
│   └───Json
│       ├───Bson
│       ├───Converters
│       ├───Linq
│       ├───Schema
│       ├───Serialization
│       └───Utilities
└───System
    ├───Linq
    └───Runtime
        └───CompilerServices
```

**Comment by Rillke** [comment]
![grafik](https://user-images.githubusercontent.com/2311611/48674816-a7354f80-eb50-11e8-97d6-ff48a2063d85.png)

**Comment by tryallthethings** [comment]
Are there any plans on releasing at least the project file(s)? Can't find those here in the repo or in the releases.

**Comment by tryallthethings** [comment]
With version #11 the project files should be complete and enable everybody to rebuild the application.
Build instructions: https://github.com/Rillke/Contact-Conversion-Wizard/wiki/Setup-Visual-Studio-and-compile-the-application
