### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by Rillke** [Rillke/Contact-Conversion-Wizard#5]
As far as I can see, this application uses Windows Forms, that's why it isn't simple to migrate from .NET Framework to .NET core? However, the [Github action setup-dotnet@v1](https://github.com/actions/setup-dotnet/issues/43) only support .NET core?

We may use
- https://help.github.com/en/articles/creating-a-docker-container-action
- FROM mcr.microsoft.com/dotnet/framework/sdk:4.8

for CI/CD then. The [sdk:4.8 docker](https://github.com/microsoft/dotnet-framework-docker/blob/master/4.8/sdk/windowsservercore-1903/Dockerfile) file looks quite complex so installing .NET might not be that easy.

**Comment by tryallthethings** [comment]
Have you checked out [Travis](https://travis-ci.org/)?
-> https://travis-ci.org/tryallthethings/Contact-Conversion-Wizard

**Comment by Rillke** [comment]
@tryallthethings Thank you! Following the invitation, you should now have access to this repo.
