### ISSUE TITLE
Bug: TEL;TYPE="something-in-quotes" in vcard is not properly recognized

### ISSUE THREAD

**Issue by jkischel** [Rillke/Contact-Conversion-Wizard#9]
Currently, Nextcloud does its .vcf export phone numbers like this example:

`TEL;TYPE="WORK,VOICE";VALUE=UNKNOWN:+49123456789
`
which will not be recognized because of the quotes.

In form1.cs, you could change the line 1426 to

`switch (type.Replace("\"", ""))`

that would do the job, but maybe there is a better place for doing the replace, so I don't add a pull request.

**Comment by tryallthethings** [comment]
I just looked into this (better late than never :smile: ) and I'm able to reproduce this. There's an issue over on the Nextcloud contacts app GitHub: https://github.com/nextcloud/contacts/issues/1107 as the export is not following the RFC.

Meanwhile, I added a configuration option to apply the fix you've mentioned upon .vcf import. Will be available in the next release.

**Comment by tryallthethings** [comment]
Please try with https://github.com/Rillke/Contact-Conversion-Wizard/releases/tag/3.5.0.2
There's a setting in the configuration dialogue

**Comment by tryallthethings** [comment]
@jkischel Did you get a chance to try this?

**Comment by jkischel** [comment]
Sorry for my late reply. With the setting "Apply fix for malformatted .vcf contacts" the import works.

just to mention: this is not an Outlook specific effect. Also some Huawei smart phones and Nextcloud Contacts are exporting quoted descriptors. 

However, as this now works, this issue can be closed.

**Comment by tryallthethings** [comment]
No worries. Thank you for testing!
